[package]
name = "sasm"
version = "0.1.0"
edition = "2021"

[dependencies]
eframe = "0.29.1"
egui = "0.29.1"
leb128 = "0.2.5"
log = "0.4.22"
monostate = "0.1.13"
pretty_env_logger = "0.5.0"
serde = { version = "1.0.214", features = ["derive"] }
serde_json = "1.0.132"
